#!/bin/bash

mkdir -p /opt/skystack/etc
userdata=/opt/skystack/etc/userdata.conf
cat > $userdata <<EOF
SS_SERVER_ID=$SS_SERVER_ID
SS_STACK_ID=$SS_STACK_ID
SS_ALIAS=$SS_ALIAS
SS_HOST=$SS_HOST
SS_APIUSER=$SS_APIUSER
SS_APITOKEN=$SS_APITOKEN
SS_APIPASS=$SS_APIPASS
SS_BASE=$SS_BASE
SS_ROLE=$SS_ROLE
SS_ENVIRONMENT=$SS_ENVIRONMENT
SS_JURISDICTION=$SS_JURISDICTION
SS_CFGM=$SS_CFGM
SS_CLOUD=$SS_CLOUD
SS_OUTPOST_VER=$SS_OUTPOST_VER
SS_COOKBOOK_VER=$SS_COOKBOOK_VER
SS_BOOTSTRAPPER_VER=$SS_BOOTSTRAPPER_VER
SS_PCKG_MAN=$SS_PCKG_MAN
EOF